### ISSUE TITLE
How  can I restore wallet.dat

### ISSUE THREAD

**Issue by qiluge** [ontio/cyano-wallet#9]
when I import wallet to cyano in chrome plugin, it overwrite my existed account, how can I restore it?

**Comment by backslash47** [comment]
Hello, 
Importing wallet will overwrite the whole wallet. That means all accounts and identities.

To restore a wallet use the import wallet again with previously exported wallet. It should support also wallet files from different wallet software (ONTO and maybe others)

**Comment by qiluge** [comment]
my priv account is permanent loss...
